data:
  train_dir: "data/dataset/train"
  val_dir: "data/dataset/val"

train:
  epochs: 100
  batch_size: 64
  lr: 0.0005
  num_workers: 4
  seed: 42
  save_dir: "weights"
  log_dir: "logs"

loss:
  beta: 0.5 # 0.0 ~ 1.0 ｜ w_k ∝ n_k^(-β) | β=0なら補正しない

model:
  output_dim: 1
