data:
  train_dir: "data/dataset/train"
  val_dir: "data/dataset/val"

train:
  epochs: 100
  batch_size: 64
  lr: 0.0005
  num_workers: 4
  seed: 42
  save_dir: "weights"
  log_dir: "logs"

loss:
  steer_weight: 1.0
  linear_weight: 1.0

model:
  output_dim: 2
