launch: #起動パラメータ
  ros__parameters:
    joy: false
    vectornav : false
    odrive : false
    socketcan : false

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    # 並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max:
      vel : 5.0
      acc: 5.0
      jer: 0.0
    # 舵角  位置[deg]
    steering_max :
      pos : 7.0

    tread : 0.6
    wheelbase : 0.8


controller_node:
  ros__parameters:
    linear_max_vel : 5.0  #[m/s]

chassis_driver_node:
  ros__parameters:
    interval_ms : 2
    wheel_radius : 0.124
    reduction_ratio : 1.0
    reverse_left_flag : false
    reverse_right_flag : false
    caster:
      max_count : 16384
      gear_ratio : 0.59090909090909
      wheel_radius : 0.12 # [m]
      reel_radius : 0.02 # [m]
      steering_radius : 0.032 # [m]
      preload_length : 0.02 # [m]
      preload_gain : 0.1
    drive_pid:
      p_gain : 6.0
      i_gain : 0.0
      d_gain : 5.0

socketcan_interface_node:
  ros__parameters:
    if_name : "can_main"


# 経路追従・追従
pure_pursuit_node:
  ros__parameters:

    lookahead_distance : 2.0
path_publisher_node:
  ros__parameters:
    interval_ms : 1000
    path_file_name : "precourse"

gnssnav_follower_node:
  ros__parameters:
    debug_flag : false
    interval_ms : 50
    lookahead_gain : 1.0
    p_gain : 1.5
    i_gain : 0.5
    d_gain : 0.2
    min_lookahead_distance : 3.0
    max_linear_vel : 2.0
    max_angular_vel : 1.57
    laps : 3
