<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>road_detector</name>
  <version>0.1.0</version>
  <description>YOLOPv2(TensorRT)で白線マスクを推論して配信するノード</description>
  <maintainer email="s25s1045sc@chibateck.ac.jp">Kyo Yamashita</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>camera_utility</depend>
  <depend>cv_bridge</depend>
  <depend>OpenCV</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
