controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController


motor_position_controller:
  ros__parameters:
    joints:
      - motor_spin_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.01
      motor_spin_joint:
        goal: 0.03

