controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    motor_position_controller:
      type: forward_command_controller/ForwardCommandController

motor_position_controller:
  ros__parameters:
    joints: 
      - motor_spin_joint
    interface_name: position
