controller_manager:
  ros_paramters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    motor_spin_controller:
      type: motor_spin/MotorSpin

motor_spin_controller:
  ros_parametrs:
    joint: motor_spin_joint
