controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    motor_velocity_controller:
      type: velocity_controllers/JointVelocityController

motor_velocity_controller:
  ros__parameters:
    joint: motor_joint

