controller_manager:
  ros__parameters:
    update_rate: 500  # 制御周期 [Hz]
    motor_position_controller:
      type: position_controllers/JointPositionController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
motor_position_controller:
  ros__parameters:
    joints:
      - motor_spin_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      motor_spin_joint:
        p: 30.0
        i: 0.0
        d: 5.0

