<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>object_detection</name>
  <version>0.1.0</version>
  <description>YOLOX(TensorRT)でパイロンを検出し、bbox底辺を地面へ投影して base_link 座標で出力するノード</description>
  <maintainer email="kasai@example.com">kasai</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>camera_utility</depend>
  <depend>cv_bridge</depend>
  <depend>object_detection_msgs</depend>
  <depend>OpenCV</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>
  <depend>visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
