<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>main_executor</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="hogehoge@gmail.com">cmos</maintainer>
  <license>TODO: License declaration</license>

  <build_depend>rclcpp</build_depend>
  <exec_depend>rclcpp</exec_depend>

  <depend>controller</depend>
  <depend>frenet_planner</depend>
  <depend>path_tracker</depend>
  <depend>utilities</depend>
  <depend>lane_line_publisher</depend>
  <depend>pose_estimater</depend>
  <depend>ekf_localizer</depend>
  <depend>trajectory_follower</depend>
  <depend>mission_planner</depend>
  <depend>local_planner</depend>
  <depend>object_detection</depend>
  <depend>zed_wrapper</depend>
  <depend>road_detector</depend>
  <depend>vectormap_server</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
