<?xml version="1.0"?>
<package format="3">
	<name>obstacle_recognition</name>
	<version>0.1.0</version>
	<description>Obstacle recognition node for aiformula perception stack.</description>

	<maintainer email="kasai@example.com">kasai</maintainer>
	<license>BSD-3-Clause</license>

	<buildtool_depend>ament_python</buildtool_depend>

	<!-- Build dependencies -->
	<exec_depend>rclpy</exec_depend>
	<exec_depend>sensor_msgs</exec_depend>
	<exec_depend>visualization_msgs</exec_depend>
	<exec_depend>object_detection_msgs</exec_depend>
	<exec_depend>cv_bridge</exec_depend>

	<export>
		<build_type>ament_python</build_type>
	</export>
</package>
